events {}

http {
    upstream accounts {
        server accounts:8001; # Сервис аккаунтов
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://accounts;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            return 404;
        }
    }
}
