worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Define upstreams for services
    upstream accounts {
        server issues:8001;
    }
    
    upstream issues {
        server issues:8002;
    }

    upstream files {
        server files:8003;
    }

    upstream emails {
        server emails:8004;
    }

    upstream notifications {
        server notifications:8005;
    }

    # Add CORS headers globally
    add_header Access-Control-Allow-Origin "http://127.0.0.1:5500";
    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, DELETE, PUT";
    add_header Access-Control-Allow-Headers "Content-Type, Authorization";
    
    server {
        listen 80;

        # Proxy requests for issues module (backend project)
        location /accounts/ {
            proxy_pass http://accounts/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        location /issues/ {
            proxy_pass http://issues/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Proxy requests for files (FileService project)
        location /files/ {
            proxy_pass http://files/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Proxy requests for emails (EmailNotification project)
        location /emails/ {
            proxy_pass http://emails/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Proxy requests for notifications (Notification project)
        location /notifications/ {
            proxy_pass http://notifications/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}
