name: Архитектурное решение
title: "[Design]: "
description: Предложить архитектурную задачу
labels: ["design", "architecture"]
projects: ["SachkovTech"]
body:
  - type: textarea
    id: problem-definition
    attributes:
      label: В чем суть задачи?
      description: Опиши проблему или требование, для которого требуется архитектурное решение.
      placeholder: Опиши задачу!
      value: "Я предлагаю рассмотреть данную проблему."
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Какое предложение ты даешь?
      description: Опиши своё предложение по решению архитектурной задачи.
      placeholder: "Например: использовать новую библиотеку, изменить структуру и т. д."
    validations:
      required: false
  - type: dropdown
    id: priority-level
    attributes:
      label: Приоритет
      description: Какой приоритет ты думаешь стоит дать этой задаче?
      options:
        - P0 (Очень важно, 1-3 дня)
        - P1 (Важно, 3-7 дней)
        - P2 (Требуется решить в течение недели)
        - P3 (Желательно решить в течение месяца)
        - P4 (Когда-нибудь)
      default: 3
    validations:
      required: true
  - type: dropdown
    id: story-points
    attributes:
      label: Количество сторипоинтов (Story Points)
      description: Оцени сколько сторипоинтов (SP) потребуется для выполнения этой задачи. Укажи от 0 до 20.
      options:
        - 1/2
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 20+
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Дополнительный контекст
      description: Добавь дополнительные детали, ссылки на документацию или другие полезные материалы.
      placeholder: Вставь здесь ссылки или материалы!
    validations:
      required: false
