// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserProgressService.Infrastructure;

#nullable disable

namespace UserProgressService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241127142709_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserProgressService.Domain.IssueAchievements.Entities.IssuesAchievementConditions", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("difficulty");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("interval")
                        .HasColumnName("time");

                    b.Property<DateOnly>("UserActivityDate")
                        .HasColumnType("date")
                        .HasColumnName("user_activity_date");

                    b.Property<Guid>("issue_achievement_id")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_achievement_id");

                    b.HasKey("Id")
                        .HasName("pk_issues_achievement_conditions");

                    b.HasIndex("issue_achievement_id")
                        .HasDatabaseName("ix_issues_achievement_conditions_issue_achievement_id");

                    b.ToTable("issues_achievement_conditions", (string)null);
                });

            modelBuilder.Entity("UserProgressService.Domain.IssueAchievements.IssueAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("created_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("user_progress_id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_progress_id");

                    b.HasKey("Id")
                        .HasName("pk_issue_achievement");

                    b.HasIndex("user_progress_id")
                        .HasDatabaseName("ix_issue_achievement_user_progress_id");

                    b.ToTable("issue_achievement", (string)null);
                });

            modelBuilder.Entity("UserProgressService.Domain.UserIssuesProgress.Entities.IssueProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("ExecutionTime")
                        .HasColumnType("interval")
                        .HasColumnName("execution_time");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<DateTime>("StartedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_date");

                    b.Property<int>("TryCount")
                        .HasColumnType("integer")
                        .HasColumnName("try_count");

                    b.Property<Guid>("user_issue_progress_id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_issue_progress_id");

                    b.HasKey("Id")
                        .HasName("pk_issue_progress");

                    b.HasIndex("user_issue_progress_id")
                        .HasDatabaseName("ix_issue_progress_user_issue_progress_id");

                    b.ToTable("issue_progress", (string)null);
                });

            modelBuilder.Entity("UserProgressService.Domain.UserIssuesProgress.UserIssuesProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("UserActivityDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_activity_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_issue_progress");

                    b.ToTable("user_issue_progress", (string)null);
                });

            modelBuilder.Entity("UserProgressService.Domain.UserProgress.UserProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Experience")
                        .HasColumnType("integer")
                        .HasColumnName("experience");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.HasKey("Id")
                        .HasName("pk_user_progress");

                    b.ToTable("user_progress", (string)null);
                });

            modelBuilder.Entity("UserProgressService.Domain.IssueAchievements.Entities.IssuesAchievementConditions", b =>
                {
                    b.HasOne("UserProgressService.Domain.IssueAchievements.IssueAchievement", null)
                        .WithMany("Conditions")
                        .HasForeignKey("issue_achievement_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issues_achievement_conditions_issue_achievement_issue_achie");
                });

            modelBuilder.Entity("UserProgressService.Domain.IssueAchievements.IssueAchievement", b =>
                {
                    b.HasOne("UserProgressService.Domain.UserProgress.UserProgress", null)
                        .WithMany("IssueAchievements")
                        .HasForeignKey("user_progress_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_achievement_user_progress_user_progress_id");
                });

            modelBuilder.Entity("UserProgressService.Domain.UserIssuesProgress.Entities.IssueProgress", b =>
                {
                    b.HasOne("UserProgressService.Domain.UserIssuesProgress.UserIssuesProgress", null)
                        .WithMany("IssuesProgress")
                        .HasForeignKey("user_issue_progress_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_progress_user_issue_progress_user_issue_progress_id");
                });

            modelBuilder.Entity("UserProgressService.Domain.IssueAchievements.IssueAchievement", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("UserProgressService.Domain.UserIssuesProgress.UserIssuesProgress", b =>
                {
                    b.Navigation("IssuesProgress");
                });

            modelBuilder.Entity("UserProgressService.Domain.UserProgress.UserProgress", b =>
                {
                    b.Navigation("IssueAchievements");
                });
#pragma warning restore 612, 618
        }
    }
}
