# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: SachkovTech.Backend

env:
  NUGET_USERNAME: ${{ secrets.NUGET_USERNAME }}
  NUGET_PASSWORD: ${{ secrets.NUGET_PASSWORD }}


on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: |
          dotnet restore ./AccountService/AccountService.sln
          dotnet restore ./IssueService/IssueService.sln
          dotnet restore ./CommentService/CommentService.sln
          dotnet restore ./EmailNotificationService/EmailNotificationService.sln
          dotnet restore ./FaqService/FaqService.sln
          dotnet restore ./FileService/FileService.sln
          dotnet restore ./NotificationService/NotificationService.sln
          dotnet restore ./ScheduleService/ScheduleService.sln
          dotnet restore ./Shared/Shared.sln
          dotnet restore ./TagService/TagService.sln
          dotnet restore ./TelegramBotService/TelegramBotService.sln
          dotnet restore ./UserProgressService/UserProgressService.sln
          dotnet restore ./tests/CodeAnalyzer.Tests/CodeAnalyzer.Tests.sln
          
      - name: Build
        run: |
          dotnet build ./AccountService/AccountService.sln --configuration Release --no-restore
          dotnet build ./IssueService/IssueService.sln --configuration Release --no-restore
          dotnet build ./CommentService/CommentService.sln --configuration Release --no-restore
          dotnet build ./EmailNotificationService/EmailNotificationService.sln --configuration Release --no-restore
          dotnet build ./FaqService/FaqService.sln --configuration Release --no-restore
          dotnet build ./FileService/FileService.sln --configuration Release --no-restore
          dotnet build ./NotificationService/NotificationService.sln --configuration Release --no-restore
          dotnet build ./ScheduleService/ScheduleService.sln --configuration Release --no-restore
          dotnet build ./Shared/Shared.sln --configuration Release --no-restore
          dotnet build ./TagService/TagService.sln --configuration Release --no-restore
          dotnet build ./TelegramBotService/TelegramBotService.sln --configuration Release --no-restore
          dotnet build ./UserProgressService/UserProgressService.sln --configuration Release --no-restore
          dotnet build ./tests/CodeAnalyzer.Tests/CodeAnalyzer.Tests.sln --configuration Release --no-restore

      - name: Services_Tests
        run: |
          dotnet test ./AccountService/AccountService.sln --configuration Release --no-restore
          dotnet test ./IssueService/IssueService.sln --configuration Release --no-restore
          dotnet test ./CommentService/CommentService.sln --configuration Release --no-restore
          dotnet test ./EmailNotificationService/EmailNotificationService.sln --configuration Release --no-restore
          dotnet test ./FaqService/FaqService.sln --configuration Release --no-restore
          dotnet test ./FileService/FileService.sln --configuration Release --no-restore
          dotnet test ./NotificationService/NotificationService.sln --configuration Release --no-restore
          dotnet test ./ScheduleService/ScheduleService.sln --configuration Release --no-restore
          dotnet test ./Shared/Shared.sln --configuration Release --no-restore
          dotnet test ./TagService/TagService.sln --configuration Release --no-restore
          dotnet test ./TelegramBotService/TelegramBotService.sln --configuration Release --no-restore
          dotnet test ./UserProgressService/UserProgressService.sln --configuration Release --no-restore
          dotnet test ./tests/CodeAnalyzer.Tests/CodeAnalyzer.Tests.sln --configuration Release --no-restore
          
      - name: General_Tests
        run: dotnet test ./tests/CodeAnalyzer.Tests/CodeAnalyzer.Tests.sln
